default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list-img_development

test:
  <<: *default
  database: rails-watch-list-img_test

production:
  <<: *default
  database: rails-watch-list-img_production
